### ISSUE TITLE
Configuration of RTCx on Nano 33 BLE

### ISSUE THREAD

**Issue by chibiconsulting** [stevemarple/RTCx#5]
Trying to run the RTCx example sketch on an Arduino Nano 33 BLE and I get the following error.

...\Documents\Arduino\libraries\RTCx\examples\RTCx_example\RTCx_example.ino: In function 'void setup()':

RTCx_example:37:6: error: 'F_CPU' was not declared in this scope

  if (F_CPU > 8000000UL)
...
Are there some suggested configurations for using the Nano 33 BLE boards?

**Comment by stevemarple** [comment]
I can replicate the problem. I believe it is an issue in the boards library for the Arduino Nano BLE. Whether boards are supposed to export their CPU frequency via the `F_CPU` macro is an interesting question, but every other official Arduino board that I have come across previously has done so.

I suggest you report this as an issue on the appropriate Arduino issue tracker. I could change the `RTCx` library to work around it but I expect other libraries I have published are also affected. I believe the Nano 33 BLE core is wrong but if Arduino say otherwise then I'll fix.
